mkdir -p context-files && \
rsync -R \
  ./pages/dashboard.tsx \
  ./pages/index.tsx \
  ./pages/nodes/[chainId]/[nodeid].tsx \
  ./pages/_app.tsx \
  ./config/apiKeys.ts \
  ./config/contracts.ts \
  ./config/deployments.ts \
  ./next.config.js \
  ./README.md \
  ./lib/localUtils.ts \
  ./lib/airstackData.ts \
  ./lib/chainData.ts \
  ./lib/fonts.ts \
  ./renovate.json \
  ./components/navbar.tsx \
  ./components/AllStacks.tsx \
  ./components/HeaderButtons.tsx \
  ./components/RootNodeDetails.tsx \
  ./components/BalanceList.tsx \
  ./components/AllStackComponents.tsx \
  ./components/MainContent.tsx \
  ./components/TokenBalance.tsx \
  ./components/ComposePanel.tsx \
  ./components/DM3.tsx \
  ./components/formatted-date.tsx \
  ./components/NodeDetails.tsx \
  ./components/NodeNavigationGrid.tsx \
  ./components/GridNavigation.tsx \
  ./components/logo.tsx \
  ./utils/chainUtils.ts \
  ./utils/colors.ts \
  ./utils/formatters.ts \
  ./extensions.json \
  ./postcss.config.js \
  ./tailwind.config.js \
  ./hooks/useFetchUserData.ts \
  ./hooks/useColorManagement.ts \
  ./hooks/useNodeData.ts \
  ./hooks/useRootNodes.ts \
  ./hooks/useAuth.ts \
  ./hooks/useCovalentBalances.ts \
  ./const/colors.tsx \
  ./const/envconst.tsx \
  ./const/contracts.tsx \
  ./yarn.lock \
  ./LICENSE \
  ./next-env.d.ts \
  ./tsconfig.json \
  ./types/chainData.ts \
  ./package-lock.json \
  ./package.json \
  ./styles/globals.css \
  context-files/
